In [3]:
# import numpy as np
# #from numpy.linalg import inv, lstsq

# def saddle_point(I):
#     """
#     Locate saddle point in an image patch.

#     The function identifies the subpixel centre of a cross-junction in the
#     image patch I, by fitting a hyperbolic paraboloid to the patch, and then 
#     finding the critical point of that paraboloid.

#     Note that the location of “'p' is relative to (-0.5, -0.5) ”at the upper
#     left corner of the patch, i.e., the pixels are treated as covering an 
#     area of one unit square.

#     Parameters:
#     -----------
#     I  - Single-band (greyscale) image patch as np.array (e.g., uint8, float).

#     Returns:
#     --------
#     pt  - 2x1 np.array, subpixel location of saddle point in I (x, y coords).
#     """
#     #--- FILL ME IN ---

#     m, n = I.shape
    
#     B=I.reshape((-1,1))
#     #x2 xy y2 x y 1 (m,n) begin from 0,0
#     A = np.empty((0,6))
#     for x in range(n):
#         for y in range(m):
#             A=np.vstack((A,[x**2,x*y,y**2,x,y,1]))
            
#     # w=(a,b,c,d,e,f) for parameters
#     (w,_,_,_)=np.linalg.lstsq(A, B,rcond=None)
#     (a,b,c,d,e,f)=w
#     print(w)
#     #solve the intersection
#     #[2a b],[b 2c]
#     C=np.array([[float(2*a),float(b)],[float(b),float(2*c)]])

#     D=np.array([-d,-e])

#     pt=np.linalg.inv(C).dot(D)
    
#     #------------------
    

#     return pt



In [2]:
import numpy as np
#from saddle_point import saddle_point

# Build non-smooth but noise-free test patch.
Il = np.hstack((np.ones((10, 10)), np.zeros((10, 10)))) 
Ir = np.hstack((np.zeros((10, 10)), np.ones((10, 10))))
I = np.vstack((Il, Ir))

pt = saddle_point(I)
print('Saddle point is at: (%.2f, %.2f)' % (pt[0], pt[1]))

[[ 1.80039913e-17]
 [ 1.13064616e-02]
 [ 7.06529536e-18]
 [-1.07411386e-01]
 [-1.07411386e-01]
 [ 1.52040816e+00]]
Saddle point is at: (9.50, 9.50)


//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:36: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


In [12]:
B=I.reshape((-1,1))
B.shape

(400, 1)

In [13]:
A = np.empty((0,6))
for x in range(20):
    for y in range(20):
        A=np.vstack((A,[x**2,x*y,y**2,x,y,1]))

In [14]:
A.shape

(400, 6)

In [15]:
(w,_,_,_)=np.linalg.lstsq(A, B)

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [16]:
w

array([[ 1.80039913e-17],
       [ 1.13064616e-02],
       [ 7.06529536e-18],
       [-1.07411386e-01],
       [-1.07411386e-01],
       [ 1.52040816e+00]])

In [17]:
(a,b,c,d,e,f)=w

#solve the intersection
#[2a b],[b 2c]
C=np.array([[float(2*a),float(b)],[float(b),float(2*c)]])

D=np.array([-d,-e])

pt=np.linalg.inv(C).dot(D)

In [9]:
pt


array([[9.5],
       [9.5]])

In [7]:
import numpy as np
from numpy.linalg import inv, lstsq


def saddle_point(I):
    """
    Locate saddle point in an image patch.

    The function identifies the subpixel centre of a cross-junction in the
    image patch I, by fitting a hyperbolic paraboloid to the patch, and then
    finding the critical point of that paraboloid.

    Note that the location of “'p' is relative to (-0.5, -0.5) ”at the upper
    left corner of the patch, i.e., the pixels are treated as covering an
    area of one unit square.

    Parameters:
    -----------
    I  - Single-band (greyscale) image patch as np.array (e.g., uint8, float).

    Returns:
    --------
    pt  - 2x1 np.array, subpixel location of saddle point in I (x, y coords).
    """
    # --- FILL ME IN ---

    m, n = I.shape

    # B = I.reshape((m*n,))
    # print(B)
    B=[]
    # x2 xy y2 x y 1 (m,n) begin from 0,0
    A = np.empty((0, 6))
    for x in range(0,n):
        for y in range(0,m):
            A = np.vstack((A, [x ** 2, x * y, y ** 2, x, y, 1.]))
            B.append(I[y, x])
    # w=(a,b,c,d,e,f) for parameters
    w = lstsq(A, B,rcond=None)[0]
    print(w)
    (a, b, c, d, e, f) = w
    # solve the intersection
    # [2a b],[b 2c]
    C = np.array([[float(2 * a), float(b)], [float(b), float(2 * c)]])

    D = np.array([-d, -e])

    pt = inv(C).dot(D)
    pt=pt.reshape(2,1)
    print(pt)

    # ------------------

    return pt


import numpy as np
#from saddle_point import saddle_point

# Build non-smooth but noise-free test patch.
Il = np.hstack((np.ones((10, 10)), np.zeros((10, 10)))) 
Ir = np.hstack((np.zeros((10, 10)), np.ones((10, 10))))
I = np.vstack((Il, Ir))

pt = saddle_point(I)
print('Saddle point is at: (%.2f, %.2f)' % (pt[0], pt[1]))


[ 1.80039913e-17  1.13064616e-02  7.06529536e-18 -1.07411386e-01
 -1.07411386e-01  1.52040816e+00]
[[9.5]
 [9.5]]
Saddle point is at: (9.50, 9.50)


In [8]:
print(I)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.